feat: support shared secret
adobe/helix-sidekick pull request #125
Opened 2021-11-01 10:31 UTC by rofe

Fix #124

2021-11-01 14:44 UTC, kptdobe approved these changes

2021-11-02 17:16 UTC, tripodsan commented on src/sidekick/module.js
> +   * @param {sidekickConfig} config The sidekick configuration
```suggestion
   * @param {SidekickConfig} config The sidekick configuration
```

2021-11-02 17:16 UTC, tripodsan commented on src/sidekick/module.js
> +   * @param {sidekickConfig} config The sidekick configuration
```suggestion
   * @param {SidekickConfig} config The sidekick configuration
```

2021-11-02 17:18 UTC, tripodsan commented on src/sidekick/module.js
> +      headers['x-token'] = token;
```suggestion
      headers['x-preauth-token'] = token;
```

2021-11-02 17:19 UTC, tripodsan commented on src/sidekick/module.js
> +      console.log(this.config);
```suggestion
      // console.log(this.config);
```

2021-11-02 17:22 UTC, tripodsan commented on src/sidekick/module.js
> +            api: this.isContent() ? 'preview' : 'code',
why not the `/status` api ?

2021-11-02 17:24 UTC, tripodsan requested changes
rename the token header, otherwise ok.

2021-11-02 18:22 UTC, rofe commented on src/sidekick/module.js
> +   * @param {sidekickConfig} config The sidekick configuration
This is a reference to [`sidekickConfig`](https://github.com/adobe/helix-sidekick/pull/125/files/a970ff06e1752e5dd241e1978dbb6fb8d4dc34ab#diff-2ba796749b8efb595287333808bcf9dc6b7fcaededc33a214038c961dda8c1ccR59) which is a virtual object that only exists in jsdoc...

2021-11-02 19:02 UTC, tripodsan commented on src/sidekick/module.js
> +   * @param {sidekickConfig} config The sidekick configuration
yes. but all class like structures and types should start upper case.

2021-11-12 07:17 UTC, tripodsan approved these changes

2022-01-27 07:48 UTC, tripodsan requested changes
requirements changed....

2022-02-12 14:39 UTC, closed without merging