feat: user-friendly error messages
adobe/helix-sidekick pull request #148
Opened 2021-11-23 15:27 UTC by rofe

Fix #144 

Checks for 401 and 404 errors and gives user some hints.

2021-11-23 16:53 UTC, kptdobe requested changes

2021-11-23 16:53 UTC, kptdobe commented on src/sidekick/module.js
> +                  ? 'Page not found. Check Helix access to this document or Sidekick configuration.'
It is maybe me but I had to read this one multiple times to understand what it means.

2021-11-23 16:53 UTC, kptdobe commented on src/sidekick/module.js
> +                msg = 'Failed to fetch status. Please try again later.';
```suggestion
                msg = 'Failed to fetch the page status. Please try again later.';
```

2021-11-23 16:53 UTC, kptdobe commented on src/sidekick/module.js
> +                  ? 'Page not found. Check Helix access to this document or Sidekick configuration.'
```suggestion
                  ? 'Page not found. Check if Helix has access to this document or your Sidekick configuration.'
```

2021-11-23 19:02 UTC, rofe commented on src/sidekick/module.js
> +                  ? 'Page not found. Check Helix access to this document or Sidekick configuration.'
Thanks! Tried to keep it (too) short 😄

2021-11-23 20:06 UTC, davidnuescheler approved these changes

2021-11-23 20:07 UTC, davidnuescheler commented
🥳

2021-11-24 06:34 UTC, kptdobe approved these changes

2021-11-24 07:49 UTC, merged

2021-11-24 07:52 UTC, trieloff commented
:tada: This PR is included in version 3.20.0 :tada:

The release is available on [GitHub release](https://github.com/adobe/helix-sidekick/releases/tag/v3.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: