Issue-129 - Tell gdrive users to use google-native file formats
adobe/helix-sidekick pull request #343
Opened 2022-09-22 16:17 UTC by hsaginor

Tell gdrive users to use google-native file formats

## Related Issues
https://github.com/adobe/helix-sidekick-extension/issues/129

2022-09-22 19:10 UTC, tripodsan requested changes
thanks, but I would make the `isSupportedGoogleType()` simpler.

2022-09-22 19:10 UTC, tripodsan commented on src/sidekick/module.js
> +  }
this is a bit complicated... :-)

```suggestion
  function isSupportedGoogleType(contentType) {
    return contentType in {
      'application/vnd.google-apps.document': true,
      'application/vnd.google-apps.spreadsheet': true,
    };
  }
```

or even just:

```suggestion
  function isSupportedGoogleType(contentType) {
    return contentType === 'application/vnd.google-apps.document'
      || contentType === 'application/vnd.google-apps.spreadsheet';
  }
```

2022-09-23 04:41 UTC, hsaginor commented on src/sidekick/module.js
> +  }
@tripodsan Made the simple change. Trying to figure out how these tests work. :) Thank you for reviewing.

2022-09-24 12:59 UTC, rofe requested changes

2022-09-24 12:59 UTC, rofe commented on src/sidekick/de.css
> +  content: "Vorschau fehlgeschlagen. Muss ein Google-Dokument oder eine Tabelle sein.";
I would keep this consistent with the translation on L158 above (or change both):
```suggestion
  content: "Vorschau-Generierung fehlgeschlagen. Muss ein Google-Dokument oder eine Tabelle sein.";
```

2022-09-24 12:59 UTC, rofe commented on src/sidekick/fr.css
> +  content: "La prévisualisation a échoué. Doit être un document Google ou une feuille de calcul.";
I would keep this consistent with the translation on L158 above (or change both):
```suggestion
  content: "La génération de l'aperçu a échoué. Doit être un document Google ou une feuille de calcul.";
```

2022-09-24 12:59 UTC, rofe commented on src/sidekick/module.js
> +            if (status.edit.sourceLocation.startsWith('gdrive:') && !isSupportedGoogleType(status.edit.contentType)) {
Since it's only used in a single place, do we really need a function for it?
```suggestion
            if (status.edit.sourceLocation.startsWith('gdrive:')
              && contentType !== 'application/vnd.google-apps.document'
              && contentType !== 'application/vnd.google-apps.spreadsheet') {
```

2022-09-24 23:14 UTC, hsaginor commented on src/sidekick/de.css
> +  content: "Vorschau fehlgeschlagen. Muss ein Google-Dokument oder eine Tabelle sein.";
I used google translate. This is not one of my languages. :)

2022-09-24 23:16 UTC, hsaginor commented on src/sidekick/module.js
> +            if (status.edit.sourceLocation.startsWith('gdrive:') && !isSupportedGoogleType(status.edit.contentType)) {
My thoughts were to decouple this in case other content types need to be added.

2022-09-27 06:19 UTC, rofe commented on src/sidekick/module.js
> +            if (status.edit.sourceLocation.startsWith('gdrive:') && !isSupportedGoogleType(status.edit.contentType)) {
I see. Nothing planned for now. We can still optimize when that becomes the case.

2022-09-28 04:58 UTC, tripodsan approved these changes

2022-09-28 06:31 UTC, rofe requested changes

2022-09-28 06:31 UTC, rofe commented on src/sidekick/module.js
> +            }
We could move this above the `sk.showWait()` call below, so `updatePreview()` won't even get called.

2022-09-28 06:31 UTC, rofe commented on test/preview.test.js
> +    const { popupOpened } = await test.run();
Why did you change this test?

2022-09-28 06:31 UTC, rofe commented on test/preview.test.js
> +  it('Preview plugin fails for office document from gdrive URL', async () => {
Let's move this with the other edit-specific preview tests below.
```suggestion
  it('Edit-specific preview plugin fails for office document from gdrive URL', async () => {
```

2022-09-28 06:31 UTC, rofe commented on test/preview.test.js
> +      plugin: 'preview',
Wrong plugin:
```suggestion
      plugin: 'edit-preview',
```

2022-09-28 20:28 UTC, tripodsan commented on src/sidekick/module.js
> +              && status.edit.sourceLocation.startsWith('gdrive:')
```suggestion
          if (status.edit.sourceLocation?.startsWith('gdrive:')
```

2022-09-30 19:58 UTC, rofe approved these changes

2022-10-01 08:48 UTC, merged

2022-10-01 08:52 UTC, trieloff commented
:tada: This PR is included in version 4.14.2 :tada:

The release is available on [GitHub release](https://github.com/adobe/helix-sidekick/releases/tag/v4.14.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: